{% set name = "conda-package-streaming" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 55f465e108f3f5acfbbd0331c6a42acd81d998a1706809883014058d2790aa9c

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.7
    - pip
  run:
    - zstandard >=0.15
    - python >=3.7
    # 'requests' is optional, only needed for 'url' submodule

test:
  imports:
    - conda_package_streaming.url
  commands:
    - pip check
  requires:
    - pip
    - requests

about:
  home: https://github.com/conda/conda-package-streaming
  summary: Download metadata from conda packages without transferring entire file.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-package-streaming/
  dev_url: https://github.com/conda/conda-package-streaming

extra:
  recipe-maintainers:
    - dholth
