{% set name = "conda-package-streaming" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-package-streaming/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ff53707a0409ce7d4f148ee6f656f7a90ed5ffa8a672e4d0d9c4d629ab0c7f84

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.9
    - pip
  run:
    - zstandard >=0.15
    - requests
    - python >=3.9

test:
  imports:
    - conda_package_streaming.url
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/conda-package-streaming
  summary: Download metadata from conda packages without transferring entire file.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda-incubator.github.io/conda-package-streaming/
  dev_url: https://github.com/conda-incubator/conda-package-streaming

extra:
  recipe-maintainers:
    - dholth
