{% set name = "conda-package-streaming" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 87be2b1c365a0e04d15579b9137b139f0837c52198bdba21c5ac071fc13efd75

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.7
    - pip
  run:
    - zstandard >=0.15
    - requests
    - python >=3.7

test:
  imports:
    - conda_package_streaming.url
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda/conda-package-streaming
  summary: Download metadata from conda packages without transferring entire file.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-package-streaming/
  dev_url: https://github.com/conda/conda-package-streaming

extra:
  recipe-maintainers:
    - dholth
